# Generated by Django 3.2.9 on 2022-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('postId', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heading0', models.CharField(max_length=300)),
                ('heading0text', models.CharField(max_length=3000)),
                ('heading1', models.CharField(max_length=300)),
                ('heading1text', models.CharField(max_length=3000)),
                ('heading2', models.CharField(max_length=300)),
                ('heading2text', models.CharField(max_length=3000)),
                ('date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
